In [1]:
!pip install pyspark py4j

Requirement already satisfied: pyspark in /usr/local/lib/python3.12/dist-packages (4.0.2)
Requirement already satisfied: py4j in /usr/local/lib/python3.12/dist-packages (0.10.9.9)

In [2]:
# Import SparkSession
from pyspark.sql import SparkSession
# Create a Spark Session
spark = SparkSession.builder.master("local[*]").getOrCreate()
# Check Spark Session Information
spark

In [3]:
!curl https://raw.githubusercontent.com/markumreed/colab_pyspark/main/WMT.csv >> WMT.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 89556  100 89556    0     0   178k      0 --:--:-- --:--:-- --:--:--  178k

In [4]:
import pandas as pd
pd_df = pd.read_csv("WMT.csv", on_bad_lines='skip')
pd_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       2517 non-null   object
 1   Open       2517 non-null   float64
 2   High       2517 non-null   float64
 3   Low        2517 non-null   float64
 4   Close      2517 non-null   float64
 5   Adj Close  2517 non-null   float64
 6   Volume     2517 non-null   int64
dtypes: float64(5), int64(1), object(1)
memory usage: 137.8+ KB

In [5]:
df = spark.read.csv('WMT.csv',inferSchema=True,header=True)

In [6]:
df.show()

+----------+---------+---------+---------+---------+---------+--------+
|      Date|     Open|     High|      Low|    Close|Adj Close|  Volume|
+----------+---------+---------+---------+---------+---------+--------+
|2016-01-20|61.799999|62.330002|60.200001|    60.84|53.990601|17369100|
|2016-01-21|    60.98|62.790001|    60.91|61.880001|54.913509|12089200|
|2016-01-22|62.439999|63.259998|62.130001|62.689999|55.632324| 9197500|
|2016-01-25|62.779999|    63.82|62.549999|63.450001|56.306763|12823400|
|2016-01-26|63.360001|64.470001|63.259998|     64.0|56.794834| 9441200|
|2016-01-27|64.099998|    65.18|63.889999|63.950001|56.750477|10214300|
|2016-01-28|64.029999|64.510002|    63.43|64.220001| 56.99007|11278300|
|2016-01-29|    64.75|66.529999|64.739998|66.360001|58.889149|16439100|
|2016-02-01|65.910004|    67.93|65.889999|     67.5| 59.90081|14728400|
|2016-02-02|67.300003|67.839996|66.279999|66.860001|59.332867|13585900|
|2016-02-03|67.309998|     67.5|    65.07|66.269997| 58.80928|12315600|
|2016-02-04|65.760002|66.550003|65.010002|66.419998| 58.94239|12833400|
|2016-02-05|66.860001|67.529999|65.879997|     67.0|  59.4571|14196500|
|2016-02-08|     66.5|67.150002|65.160004|66.900002|59.368362|20743600|
|2016-02-09|65.489998|66.410004|    64.68|65.809998|58.401058|14642400|
|2016-02-10|66.190002|66.589996|65.650002|65.790001| 58.38332| 9709300|
|2016-02-11|65.019997|65.760002|64.779999|    65.32|57.966228|11186700|
|2016-02-12|65.519997|    66.25|64.870003|    66.18|58.729424| 9695500|
|2016-02-16|66.610001|66.800003|     65.5|65.900002|58.480934|11360500|
|2016-02-17|66.099998|66.610001|65.809998|66.110001|58.667301|12426700|
+----------+---------+---------+---------+---------+---------+--------+
only showing top 20 rows

In [7]:
df.printSchema()

root
 |-- Date: date (nullable = true)
 |-- Open: double (nullable = true)
 |-- High: double (nullable = true)
 |-- Low: double (nullable = true)
 |-- Close: double (nullable = true)
 |-- Adj Close: double (nullable = true)
 |-- Volume: string (nullable = true)

In [8]:
pd_df.head()

         Date       Open       High        Low      Close  Adj Close    Volume
0  2016-01-20  61.799999  62.330002  60.200001  60.840000  53.990601  17369100
1  2016-01-21  60.980000  62.790001  60.910000  61.880001  54.913509  12089200
2  2016-01-22  62.439999  63.259998  62.130001  62.689999  55.632324   9197500
3  2016-01-25  62.779999  63.820000  62.549999  63.450001  56.306763  12823400
4  2016-01-26  63.360001  64.470001  63.259998  64.000000  56.794834   9441200

In [9]:
df.show(5)

+----------+---------+---------+---------+---------+---------+--------+
|      Date|     Open|     High|      Low|    Close|Adj Close|  Volume|
+----------+---------+---------+---------+---------+---------+--------+
|2016-01-20|61.799999|62.330002|60.200001|    60.84|53.990601|17369100|
|2016-01-21|    60.98|62.790001|    60.91|61.880001|54.913509|12089200|
|2016-01-22|62.439999|63.259998|62.130001|62.689999|55.632324| 9197500|
|2016-01-25|62.779999|    63.82|62.549999|63.450001|56.306763|12823400|
|2016-01-26|63.360001|64.470001|63.259998|     64.0|56.794834| 9441200|
+----------+---------+---------+---------+---------+---------+--------+
only showing top 5 rows

In [10]:
pd_df[["Date","Open"]]

            Date        Open
0     2016-01-20   61.799999
1     2016-01-21   60.980000
2     2016-01-22   62.439999
3     2016-01-25   62.779999
4     2016-01-26   63.360001
...          ...         ...
2512  2021-01-12  149.000000
2513  2021-01-13  148.750000
2514  2021-01-14  147.820007
2515  2021-01-15  145.139999
2516  2021-01-19  144.639999

[2517 rows x 2 columns]

In [11]:
df.select(["Date","Open"]) .show()

+----------+---------+
|      Date|     Open|
+----------+---------+
|2016-01-20|61.799999|
|2016-01-21|    60.98|
|2016-01-22|62.439999|
|2016-01-25|62.779999|
|2016-01-26|63.360001|
|2016-01-27|64.099998|
|2016-01-28|64.029999|
|2016-01-29|    64.75|
|2016-02-01|65.910004|
|2016-02-02|67.300003|
|2016-02-03|67.309998|
|2016-02-04|65.760002|
|2016-02-05|66.860001|
|2016-02-08|     66.5|
|2016-02-09|65.489998|
|2016-02-10|66.190002|
|2016-02-11|65.019997|
|2016-02-12|65.519997|
|2016-02-16|66.610001|
|2016-02-17|66.099998|
+----------+---------+
only showing top 20 rows

In [12]:
pd_df.loc[pd_df["Close"]<62,:]

,Date,Open,High,Low,Close,Adj Close,Volume
0,2016-01-20,61.799999,62.330002,60.200001,60.840000,53.990601,17369100
1,2016-01-21,60.980000,62.790001,60.910000,61.880001,54.913509,12089200
1258,2016-01-20,61.799999,62.330002,60.200001,60.840000,53.990601,17369100
1259,2016-01-21,60.980000,62.790001,60.910000,61.880001,54.913509,12089200

In [13]:
df2 = df.filter(df['Close'] < 62)

df2

DataFrame[Date: date, Open: double, High: double, Low: double, Close: double, Adj Close: double, Volume: string]

In [14]:
df2.show(10)

+----------+---------+---------+---------+---------+---------+--------+
|      Date|     Open|     High|      Low|    Close|Adj Close|  Volume|
+----------+---------+---------+---------+---------+---------+--------+
|2016-01-20|61.799999|62.330002|60.200001|    60.84|53.990601|17369100|
|2016-01-21|    60.98|62.790001|    60.91|61.880001|54.913509|12089200|
|2016-01-20|61.799999|62.330002|60.200001|    60.84|53.990601|17369100|
|2016-01-21|    60.98|62.790001|    60.91|61.880001|54.913509|12089200|
+----------+---------+---------+---------+---------+---------+--------+

In [15]:
pd_df.dropna(inplace=True)

In [16]:
pd_df.shape

(2517, 7)

In [17]:
df=df.na.drop(how="all")

In [18]:
df.show()

+----------+---------+---------+---------+---------+---------+--------+
|      Date|     Open|     High|      Low|    Close|Adj Close|  Volume|
+----------+---------+---------+---------+---------+---------+--------+
|2016-01-20|61.799999|62.330002|60.200001|    60.84|53.990601|17369100|
|2016-01-21|    60.98|62.790001|    60.91|61.880001|54.913509|12089200|
|2016-01-22|62.439999|63.259998|62.130001|62.689999|55.632324| 9197500|
|2016-01-25|62.779999|    63.82|62.549999|63.450001|56.306763|12823400|
|2016-01-26|63.360001|64.470001|63.259998|     64.0|56.794834| 9441200|
|2016-01-27|64.099998|    65.18|63.889999|63.950001|56.750477|10214300|
|2016-01-28|64.029999|64.510002|    63.43|64.220001| 56.99007|11278300|
|2016-01-29|    64.75|66.529999|64.739998|66.360001|58.889149|16439100|
|2016-02-01|65.910004|    67.93|65.889999|     67.5| 59.90081|14728400|
|2016-02-02|67.300003|67.839996|66.279999|66.860001|59.332867|13585900|
|2016-02-03|67.309998|     67.5|    65.07|66.269997| 58.80928|12315600|
|2016-02-04|65.760002|66.550003|65.010002|66.419998| 58.94239|12833400|
|2016-02-05|66.860001|67.529999|65.879997|     67.0|  59.4571|14196500|
|2016-02-08|     66.5|67.150002|65.160004|66.900002|59.368362|20743600|
|2016-02-09|65.489998|66.410004|    64.68|65.809998|58.401058|14642400|
|2016-02-10|66.190002|66.589996|65.650002|65.790001| 58.38332| 9709300|
|2016-02-11|65.019997|65.760002|64.779999|    65.32|57.966228|11186700|
|2016-02-12|65.519997|    66.25|64.870003|    66.18|58.729424| 9695500|
|2016-02-16|66.610001|66.800003|     65.5|65.900002|58.480934|11360500|
|2016-02-17|66.099998|66.610001|65.809998|66.110001|58.667301|12426700|
+----------+---------+---------+---------+---------+---------+--------+
only showing top 20 rows

DataFrame[name: string]

In [46]:
data = {'col1': [i for i in range(10**6)],
        'col2': [i+1 for i in range(10**6)],
        'col3': ['A' if i % 2 == 0 else 'B' for i in range(10**6)]}
df = pd.DataFrame(data)
df

          col1     col2 col3
0            0        1    A
1            1        2    B
2            2        3    A
3            3        4    B
4            4        5    A
...        ...      ...  ...
999995  999995   999996    B
999996  999996   999997    A
999997  999997   999998    B
999998  999998   999999    A
999999  999999  1000000    B

[1000000 rows x 3 columns]

In [47]:
# Convert Pandas DataFrame to PySpark DataFrame
spark_df = spark.createDataFrame(df)
spark_df

DataFrame[col1: bigint, col2: bigint, col3: string]

In [48]:
# Measure the time taken by Pandas DataFrame
%timeit pandas_filtered = df[df['col3'] == 'A']

94.9 ms ± 11.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [49]:
# Measure the time taken by PySpark DataFrame
%timeit spark_filtered = spark_df.filter(spark_df.col3 == 'A')

6.27 ms ± 888 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [19]:
from pyspark import SparkContext
sc = SparkContext.getOrCreate()

In [20]:
rdd_obj=df.rdd
print(type(rdd_obj))

<class 'pyspark.core.rdd.RDD'>

In [21]:
print(rdd_obj.getNumPartitions())

1

In [22]:
new_rdd=rdd_obj.repartition(4)
print(new_rdd.getNumPartitions())

4

In [25]:
import os
os.cpu_count()

2